Add files via upload
anushkabhatcode/Resume-Builder pull request #33
Opened 2024-12-03 15:45 UTC by Anjalipolasani

2024-12-03 16:11 UTC, pktpaulie approved these changes

2024-12-03 19:16 UTC, Kavyan17 requested changes
Thanks for the conversion Anjali.
Could you please change the hard-coded file paths for "jd_file" and "resume_file"?

2024-12-03 22:09 UTC, Anjalipolasani commented
> Thanks for the conversion Anjali. Could you please change the hard-coded file paths for "jd_file" and "resume_file"?

Yes. sure I am trying to change the hard-coded  file paths

2024-12-04 01:07 UTC, KarthikBalajiB requested changes
Thanks for the conversion Anjali. 

The function process_files should consume the pdf/docx document.  

You should only pass the JD_file_path (JD file) and Resume_file_Path (Resume file) as parameters to that function, where the input will come from the app.py.

2024-12-04 02:12 UTC, KarthikBalajiB approved these changes

2024-12-04 03:15 UTC, anushkabhatcode approved these changes

2024-12-04 05:22 UTC, Kavyan17 approved these changes

2024-12-04 05:24 UTC, merged